Fix some slicing issues
Resolved some indexing issues

Issues with initiation of 3D rendering have popped up occasionally when switching channels .
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_VALUE

Also  when activating 3D rendering with 2 colors causes channel misalignment:
ValueError: axes don't match array.  

Rendering high-channels first then turning on lower channels seems to resolve the issue. ie.  Channel 1 only then initiate 3D.  Then turn on Channel 0.